### ISSUE TITLE
Total file fitrate?

### ISSUE THREAD

**Issue by probablykasper** [GuillaumeGomez/mp3-metadata#25]
Is there any way to get the mp3 bitrate without looping through all the frames?

**Comment by GuillaumeGomez** [comment]
No, you have to loop through them.

**Comment by kasper9n** [comment]
@GuillaumeGomez Hmm, do you know if there's any way to do it using something else than `mp3-metadata`?

**Comment by GuillaumeGomez** [comment]
No idea.

**Comment by kasper9n** [comment]
Okay, thanks regardless!
